volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:17
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    platform: linux/amd64

  backend:
    image: lisaperevalova/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
      - .:/backend
    depends_on:
      - db
    platform: linux/amd64
    environment:
      - DEBUG=True

  frontend:
    env_file: .env
    image: lisaperevalova/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - db
    platform: linux/amd64

  gateway:
    image: lisaperevalova/foodgram_gateway
    build: ./nginx/
    env_file: .env
    ports:
      - 8500:80
    volumes:
      - static:/staticfiles/
      - media:/app/media
    depends_on:
      - backend
      - frontend
    platform: linux/amd64