# version: '3.3'
# services:

#   frontend:
#     container_name: foodgram_frontend
#     build: ./frontend
#     volumes:
#       - ../frontend/:/app/result_build/
#   nginx:
#     container_name: foodgram_gateway
#     image: nginx:1.25.4-alpine
#     ports:
#       - "8500:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#       - ../frontend/build:/usr/share/nginx/html/
#       - ../docs/:/usr/share/nginx/html/api/docs/

volumes:
  static:
  pg_data:
  media:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: /backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media/
    expose:
      - 80

  frontend:
    build: /frontend
    env_file: .env
    volumes:
      - static:/app/build/

  nginx:
    build: ./nginx/
    ports:
      - 8500:80
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static/
      - media:/media/
# volumes:
#   pg_data:
#   static:
#   media:
# services:
#   db:
#     image: postgres:13
#     env_file: .env
#     volumes:
#       - pg_data:/var/lib/postgresql/data
#   backend:
#     build: ./backend/
#     env_file: .env
#     volumes:
#       - static:/backend_static/
#       - media:/app/media
#   frontend:
#     env_file: .env
#     build: ./frontend/
#     command: cp -r /app/build/. /frontend_static/
#     volumes:
#       - static:/frontend_static
#   gateway:
#     build: ./nginx/
#     env_file: .env
#     ports:
#       - 8500:80
#     volumes:
#       - static:/staticfiles/
#       - media:/media